import gcn
import os

AIRMASS_LIMIT = 2.5
MARKDOWN = True
DCT_LOC_PICKLE = 'salt_loc.pickle'
DCT_ASTROPLAN_LOC_PICKLE = 'salt_astroplan_loc.pickle'
ARCHIVED_XML_DIR = "processed_xml"
OUTPUT_HTML_DIR = "output_html"
TEMPLATE_HTML_DIR = "html_templates"

HTML_TEMPLATES_DICT = {
    'astro_coords_html': 'astro_coords.html',
    'author_html': 'author.html',
    'authors_html': 'authors.html',
    'citation_html': 'citation.html',
    'citations_html': 'citations.html',
    'event_ivorn_html': 'event_ivorn.html',
    'event_ivorns_html': 'event_ivorns.html',
    'field_html': 'field.html',
    'fields_html': 'fields.html',
    'how_html': 'how.html',
    'inference_html': 'inference.html',
    'inferences_html': 'inferences.html',
    'observation_location_html': 'observation_location.html',
    'observatory_location_html': 'observatory_location.html',
    'param_html': 'param.html',
    'params_html': 'params.html',
    'position2d_html': 'position2d.html',
    'position3d_html': 'position3d.html',
    'reference_html': 'reference.html',
    'references_html': 'references.html',
    'table_html': 'table.html',
    'tables_html': 'tables.html',
    'time_instant_html': 'time_instant.html',
    'voevent_html': 'voevent.html',
    'what_html': 'what.html',
    'wherewhen_html': 'wherewhen.html',
    'who_html': 'who.html',
    'why_html': 'why.html',
    'icon_html': 'icon.html',
    'modal_html': 'modal.html',
    'groups_html': 'groups.html',
    'group_html': 'group.html',
    'container_html': 'container.html',
    'simple_row_html': 'simple_row.html',
}

if MARKDOWN:
    for k, v in HTML_TEMPLATES_DICT.items():
        HTML_TEMPLATES_DICT[k] = v.replace('.html', '.md')
    OUTPUT_HTML_DIR = "output_md"
    TEMPLATE_HTML_DIR = "markdown_templates"

for k, v in HTML_TEMPLATES_DICT.items():
    HTML_TEMPLATES_DICT[k] = os.path.join(TEMPLATE_HTML_DIR, v)

for directory in [ARCHIVED_XML_DIR, OUTPUT_HTML_DIR]:
    if not os.path.isdir(directory):
        os.makedirs(directory)

EXCLUDED_NOTICE_TYPES = (
    # gcn.notice_types.SWIFT_TOO_FOM,
    # gcn.notice_types.SWIFT_TOO_SC_SLEW,
    # gcn.notice_types.SWIFT_BAT_GRB_LC,
    # gcn.notice_types.SWIFT_BAT_SCALEDMAP,
    # gcn.notice_types.SWIFT_FOM_OBS,
    # gcn.notice_types.SWIFT_SC_SLEW,
    # gcn.notice_types.SWIFT_XRT_POSITION,
    # gcn.notice_types.SWIFT_XRT_SPECTRUM,
    # gcn.notice_types.SWIFT_XRT_IMAGE,
    # gcn.notice_types.SWIFT_XRT_LC,
    # gcn.notice_types.SWIFT_XRT_CENTROID,
    # gcn.notice_types.SWIFT_UVOT_DBURST,
    # gcn.notice_types.SWIFT_UVOT_FCHART,
    # gcn.notice_types.SWIFT_BAT_GRB_LC_PROC,
    # gcn.notice_types.SWIFT_XRT_SPECTRUM_PROC,
    # gcn.notice_types.SWIFT_XRT_IMAGE_PROC,
    # gcn.notice_types.SWIFT_UVOT_DBURST_PROC,
    # gcn.notice_types.SWIFT_UVOT_FCHART_PROC,
    # gcn.notice_types.SWIFT_UVOT_POS,
    # gcn.notice_types.SWIFT_BAT_GRB_POS_TEST,
    # gcn.notice_types.SWIFT_POINTDIR,
    # gcn.notice_types.SWIFT_BAT_TRANS,
    # gcn.notice_types.SWIFT_XRT_THRESHPIX,
    # gcn.notice_types.SWIFT_XRT_THRESHPIX_PROC,
    # gcn.notice_types.SWIFT_XRT_SPER,
    # gcn.notice_types.SWIFT_XRT_SPER_PROC,
    # gcn.notice_types.SWIFT_UVOT_POS_NACK,
    # gcn.notice_types.SWIFT_BAT_ALARM_SHORT,
    # gcn.notice_types.SWIFT_BAT_ALARM_LONG,
    # gcn.notice_types.SWIFT_UVOT_EMERGENCY,
    # gcn.notice_types.SWIFT_XRT_EMERGENCY,
    # gcn.notice_types.SWIFT_FOM_PPT_ARG_ERR,
    # gcn.notice_types.SWIFT_FOM_SAFE_POINT,
    # gcn.notice_types.SWIFT_FOM_SLEW_ABORT,
    # gcn.notice_types.SWIFT_BAT_QL_POS,
    # gcn.notice_types.SWIFT_BAT_SUB_THRESHOLD,
    # gcn.notice_types.SWIFT_BAT_SLEW_POS,
    # gcn.notice_types.SWIFT_BAT_GRB_ALERT,
    # gcn.notice_types.SWIFT_ACTUAL_POINTDIR,
    # gcn.notice_types.SWIFT_BAT_MONITOR,
    # gcn.notice_types.SWIFT_BAT_SUBSUB,
    # gcn.notice_types.SWIFT_BAT_KNOWN_SRC,
    gcn.notice_types.GRB_COORDS,
    gcn.notice_types.TEST_COORDS,
    gcn.notice_types.IM_ALIVE,
    gcn.notice_types.KILL_SOCKET,
    gcn.notice_types.MAXBC,
    gcn.notice_types.BRAD_COORDS,
    gcn.notice_types.GRB_FINAL,
    gcn.notice_types.HUNTS_SRC,
    gcn.notice_types.ALEXIS_SRC,
    gcn.notice_types.XTE_PCA_ALERT,
    gcn.notice_types.XTE_PCA_SRC,
    gcn.notice_types.XTE_ASM_ALERT,
    gcn.notice_types.XTE_ASM_SRC,
    gcn.notice_types.COMPTEL_SRC,
    gcn.notice_types.IPN_RAW,
    gcn.notice_types.IPN_SEG,
    gcn.notice_types.SAX_WFC_ALERT,
    gcn.notice_types.SAX_WFC_SRC,
    gcn.notice_types.SAX_NFI_ALERT,
    gcn.notice_types.SAX_NFI_SRC,
    gcn.notice_types.XTE_ASM_TRANS,
    gcn.notice_types.spare38,
    gcn.notice_types.IPN_POS,
    gcn.notice_types.HETE_ALERT_SRC,
    gcn.notice_types.HETE_UPDATE_SRC,
    gcn.notice_types.HETE_FINAL_SRC,
    gcn.notice_types.HETE_GNDANA_SRC,
    gcn.notice_types.HETE_TEST,
    gcn.notice_types.GRB_CNTRPART,
    gcn.notice_types.DOW_TOD,
    gcn.notice_types.spare50,
    gcn.notice_types.INTEGRAL_POINTDIR,
    gcn.notice_types.INTEGRAL_SPIACS,
    gcn.notice_types.INTEGRAL_WAKEUP,
    gcn.notice_types.INTEGRAL_REFINED,
    gcn.notice_types.INTEGRAL_OFFLINE,
    gcn.notice_types.INTEGRAL_WEAK,
    gcn.notice_types.AAVSO,
    gcn.notice_types.MILAGRO_POS,
    gcn.notice_types.KONUS_LC,
    gcn.notice_types.SWIFT_BAT_GRB_POS_ACK,
    gcn.notice_types.SWIFT_BAT_GRB_POS_NACK,
    gcn.notice_types.AGILE_GRB_WAKEUP,
    gcn.notice_types.AGILE_GRB_GROUND,
    gcn.notice_types.AGILE_GRB_REFINED,
    gcn.notice_types.AGILE_POINTDIR,
    gcn.notice_types.AGILE_TRANS,
    gcn.notice_types.AGILE_GRB_POS_TEST,
    gcn.notice_types.FERMI_GBM_ALERT,
    gcn.notice_types.FERMI_GBM_FLT_POS,
    gcn.notice_types.FERMI_GBM_GND_POS,
    gcn.notice_types.FERMI_GBM_LC,
    gcn.notice_types.FERMI_GBM_GND_INTERNAL,
    gcn.notice_types.FERMI_GBM_FIN_POS,
    gcn.notice_types.FERMI_GBM_ALERT_INTERNAL,
    gcn.notice_types.FERMI_GBM_FLT_INTERNAL,
    gcn.notice_types.FERMI_GBM_TRANS,
    gcn.notice_types.FERMI_GBM_POS_TEST,
    gcn.notice_types.FERMI_LAT_POS_INI,
    gcn.notice_types.FERMI_LAT_POS_UPD,
    gcn.notice_types.FERMI_LAT_POS_DIAG,
    gcn.notice_types.FERMI_LAT_TRANS,
    gcn.notice_types.FERMI_LAT_POS_TEST,
    gcn.notice_types.FERMI_LAT_MONITOR,
    gcn.notice_types.FERMI_SC_SLEW,
    gcn.notice_types.FERMI_LAT_GND,
    gcn.notice_types.FERMI_LAT_OFFLINE,
    gcn.notice_types.FERMI_POINTDIR,
    gcn.notice_types.SIMBADNED,
    gcn.notice_types.FERMI_GBM_SUBTHRESH,
    gcn.notice_types.MAXI_UNKNOWN,
    gcn.notice_types.MAXI_KNOWN,
    gcn.notice_types.MAXI_TEST,
    gcn.notice_types.OGLE,
    gcn.notice_types.CBAT,
    gcn.notice_types.MOA,
    gcn.notice_types.VOE_11_IM_ALIVE,
    gcn.notice_types.VOE_20_IM_ALIVE,
    gcn.notice_types.FERMI_SC_SLEW_INTERNAL,
    gcn.notice_types.COINCIDENCE,
    gcn.notice_types.FERMI_GBM_FIN_INTERNAL,
    gcn.notice_types.SUZAKU_LC,
    gcn.notice_types.SNEWS,
    gcn.notice_types.LVC_PRELIMINARY,
    gcn.notice_types.LVC_INITIAL,
    gcn.notice_types.LVC_UPDATE,
    gcn.notice_types.LVC_TEST,
    gcn.notice_types.LVC_COUNTERPART,
    gcn.notice_types.AMON_ICECUBE_COINC,
    gcn.notice_types.AMON_ICECUBE_HESE,
    gcn.notice_types.CALET_GBM_FLT_LC,
    gcn.notice_types.CALET_GBM_GND_LC,
    gcn.notice_types.AMON_ICECUBE_EHE,
    # gcn.notice_types.AMON_TEST_EVENT,
)

INCLUDE_ALERT_MESSAGES = (
    gcn.notice_types.SWIFT_POINTDIR,
    gcn.notice_types.SWIFT_ACTUAL_POINTDIR,
    gcn.notice_types.SWIFT_SC_SLEW,
    gcn.notice_types.SWIFT_TOO_SC_SLEW,
    gcn.notice_types.SWIFT_TOO_FOM,
    gcn.notice_types.SWIFT_BAT_ALARM_LONG,
    gcn.notice_types.SWIFT_BAT_ALARM_SHORT,
    gcn.notice_types.SWIFT_BAT_GRB_ALERT,
    gcn.notice_types.SWIFT_BAT_GRB_LC,
    gcn.notice_types.SWIFT_BAT_GRB_LC_PROC,
    gcn.notice_types.SWIFT_BAT_GRB_POS_TEST,
    gcn.notice_types.SWIFT_BAT_KNOWN_SRC,
    gcn.notice_types.SWIFT_BAT_MONITOR,
    gcn.notice_types.SWIFT_BAT_QL_POS,
    gcn.notice_types.SWIFT_BAT_SCALEDMAP,
    gcn.notice_types.SWIFT_BAT_SLEW_POS,
    gcn.notice_types.SWIFT_BAT_SUBSUB,
    gcn.notice_types.SWIFT_BAT_SUB_THRESHOLD,
    gcn.notice_types.SWIFT_BAT_TRANS,
    gcn.notice_types.SWIFT_FOM_OBS,
    gcn.notice_types.SWIFT_FOM_PPT_ARG_ERR,
    gcn.notice_types.SWIFT_FOM_SAFE_POINT,
    gcn.notice_types.SWIFT_FOM_SLEW_ABORT,
    gcn.notice_types.SWIFT_UVOT_DBURST,
    gcn.notice_types.SWIFT_UVOT_DBURST_PROC,
    gcn.notice_types.SWIFT_UVOT_EMERGENCY,
    gcn.notice_types.SWIFT_UVOT_FCHART,
    gcn.notice_types.SWIFT_UVOT_FCHART_PROC,
    gcn.notice_types.SWIFT_UVOT_POS,
    gcn.notice_types.SWIFT_UVOT_POS_NACK,
    gcn.notice_types.SWIFT_XRT_CENTROID,
    gcn.notice_types.SWIFT_XRT_EMERGENCY,
    gcn.notice_types.SWIFT_XRT_IMAGE,
    gcn.notice_types.SWIFT_XRT_IMAGE_PROC,
    gcn.notice_types.SWIFT_XRT_LC,
    gcn.notice_types.SWIFT_XRT_POSITION,
    gcn.notice_types.SWIFT_XRT_SPECTRUM,
    gcn.notice_types.SWIFT_XRT_SPECTRUM_PROC,
    gcn.notice_types.SWIFT_XRT_SPER,
    gcn.notice_types.SWIFT_XRT_SPER_PROC,
    gcn.notice_types.SWIFT_XRT_THRESHPIX,
    gcn.notice_types.SWIFT_XRT_THRESHPIX_PROC,
    gcn.notice_types.FERMI_GBM_ALERT,
    gcn.notice_types.FERMI_GBM_FLT_POS,
    gcn.notice_types.FERMI_GBM_GND_POS,
    gcn.notice_types.FERMI_GBM_LC,
    gcn.notice_types.FERMI_GBM_GND_INTERNAL,
    gcn.notice_types.FERMI_GBM_FIN_POS,
    gcn.notice_types.FERMI_GBM_ALERT_INTERNAL,
    gcn.notice_types.FERMI_GBM_FLT_INTERNAL,
    gcn.notice_types.FERMI_GBM_TRANS,
    gcn.notice_types.FERMI_GBM_POS_TEST,
    gcn.notice_types.FERMI_LAT_POS_INI,
    gcn.notice_types.FERMI_LAT_POS_UPD,
    gcn.notice_types.FERMI_LAT_POS_DIAG,
    gcn.notice_types.FERMI_LAT_TRANS,
    gcn.notice_types.FERMI_LAT_POS_TEST,
    gcn.notice_types.FERMI_LAT_MONITOR,
    gcn.notice_types.FERMI_SC_SLEW,
    gcn.notice_types.FERMI_LAT_GND,
    gcn.notice_types.FERMI_LAT_OFFLINE,
    gcn.notice_types.FERMI_POINTDIR,
)

